version: '3'

tasks:
  clean:
    desc: "Nettoyer le projet"
    cmds:
      - ./gradlew clean

  build:
    desc: "Compiler l'application en mode debug"
    cmds:
      - ./gradlew :composeApp:assembleDebug

  build-release:
    desc: "Compiler l'application en mode release"
    cmds:
      - ./gradlew :composeApp:assembleRelease

  install:
    desc: "Installer l'application sur un appareil connecté"
    deps: [build]
    cmds:
      - ./gradlew :composeApp:installDebug

  run:
    desc: "Compiler et lancer l'application"
    cmds:
      - ./gradlew :composeApp:installDebug
      - adb shell am start -n com.linkkeeper.app/MainActivity

  uninstall:
    desc: "Désinstaller l'application"
    cmds:
      - adb uninstall com.linkkeeper.app

  devices:
    desc: "Lister les appareils connectés"
    cmds:
      - adb devices

  logs:
    desc: "Afficher les logs de l'application"
    cmds:
      - adb logcat -s LinkKeeper:* AndroidRuntime:E

  check:
    desc: "Vérifier le code (lint, tests)"
    cmds:
      - ./gradlew check

  dependencies:
    desc: "Afficher l'arbre des dépendances"
    cmds:
      - ./gradlew :composeApp:dependencies

  gradle-wrapper:
    desc: "Générer le wrapper Gradle"
    cmds:
      - gradle wrapper --gradle-version 8.5

  setup:
    desc: "Configuration initiale du projet"
    cmds:
      - task: gradle-wrapper
      - chmod +x gradlew
      - ./gradlew --version

  rebuild:
    desc: "Nettoyer et recompiler"
    cmds:
      - task: clean
      - task: build

  # ── Backend ──────────────────────────────────────────────
  backend:
    desc: "Lancer le backend Go (gRPC + HTTP gateway)"
    dir: backend
    dotenv: ['backend/.env.example']
    cmds:
      - go run ./cmd/server

  backend:build:
    desc: "Compiler le backend"
    dir: backend
    cmds:
      - go build -o ../build/server ./cmd/server

  backend:proto:
    desc: "Générer le code protobuf"
    dir: backend
    cmds:
      - buf generate

  # ── Frontend ─────────────────────────────────────────────
  frontend:dev:
    desc: "Lancer le frontend en mode développement"
    dir: frontend
    cmds:
      - npm run dev

  frontend:build:
    desc: "Compiler le frontend pour la production"
    dir: frontend
    cmds:
      - npm run build

  frontend:install:
    desc: "Installer les dépendances frontend"
    dir: frontend
    cmds:
      - npm install

  # ── Ollama ───────────────────────────────────────────────
  ollama:
    desc: "Démarrer Ollama en Docker + pull qwen2.5:3b (optimisé CPU, 8Go RAM)"
    vars:
      MODEL: '{{.OLLAMA_MODEL | default "qwen2.5:3b"}}'
    env:
      OLLAMA_MODEL: "{{.MODEL}}"
    cmds:
      - |
        if docker ps -q -f name=tribbae-ollama | grep -q .; then
          echo "Ollama deja en cours d'execution"
        elif docker ps -aq -f name=tribbae-ollama | grep -q .; then
          echo "Redemarrage du conteneur Ollama existant..."
          docker start tribbae-ollama
        else
          echo "Creation du conteneur Ollama..."
          docker run -d \
            --name tribbae-ollama \
            --restart unless-stopped \
            -p 11434:11434 \
            -v ollama_data:/root/.ollama \
            -e OLLAMA_NUM_PARALLEL=1 \
            -e OLLAMA_MAX_LOADED_MODELS=1 \
            ollama/ollama
        fi
      - |
        echo "Attente du demarrage d'Ollama..."
        for i in $(seq 1 15); do
          if docker exec tribbae-ollama ollama list >/dev/null 2>&1; then
            echo "Ollama pret"
            break
          fi
          sleep 2
        done
      - |
        echo "Pull du modele $OLLAMA_MODEL (premiere fois : ~2 Go)..."
        docker exec tribbae-ollama ollama pull "$OLLAMA_MODEL"
        echo "Ollama pret -> http://localhost:11434 (modele: $OLLAMA_MODEL)"

  ollama:stop:
    desc: "Arreter le conteneur Ollama"
    cmds:
      - docker stop tribbae-ollama
      - echo "Ollama arrete"

  ollama:rm:
    desc: "Supprimer le conteneur Ollama (garde les modeles dans le volume)"
    cmds:
      - docker rm -f tribbae-ollama
      - echo "Conteneur supprime (volume ollama_data conserve)"

  ollama:logs:
    desc: "Afficher les logs Ollama"
    cmds:
      - docker logs -f tribbae-ollama

  ollama:models:
    desc: "Lister les modeles Ollama disponibles"
    cmds:
      - docker exec tribbae-ollama ollama list

  # ── SearXNG (recherche web) ──────────────────────────────
  searxng:
    desc: "Demarrer SearXNG en Docker (moteur de recherche web)"
    cmds:
      - |
        if docker ps -q -f name=tribbae-searxng | grep -q .; then
          echo "SearXNG deja en cours d'execution"
        elif docker ps -aq -f name=tribbae-searxng | grep -q .; then
          echo "Redemarrage du conteneur SearXNG existant..."
          docker start tribbae-searxng
        else
          echo "Creation du conteneur SearXNG..."
          docker run -d \
            --name tribbae-searxng \
            --restart unless-stopped \
            -p 8888:8080 \
            -v searxng_data:/etc/searxng \
            -e SEARXNG_BASE_URL=http://localhost:8888/ \
            searxng/searxng
        fi
      - |
        echo "Attente du demarrage de SearXNG..."
        for i in $(seq 1 15); do
          if curl -sf http://localhost:8888/healthz >/dev/null 2>&1; then
            echo "SearXNG pret -> http://localhost:8888"
            break
          fi
          sleep 2
        done

  searxng:stop:
    desc: "Arreter le conteneur SearXNG"
    cmds:
      - docker stop tribbae-searxng
      - echo "SearXNG arrete"

  searxng:rm:
    desc: "Supprimer le conteneur SearXNG"
    cmds:
      - docker rm -f tribbae-searxng
      - echo "Conteneur SearXNG supprime"

  # ── Dev (tout en un) ─────────────────────────────────────
  dev:
    desc: "Demarrer tout l'environnement de dev (SearXNG + Ollama + backend + frontend)"
    cmds:
      - task: searxng
      - task: ollama
      - echo "Démarrage du backend..."
      - cmd: |
          cd backend && \
          export $(cat .env.example | grep -v '^#' | xargs) && \
          go run ./cmd/server &
          echo $! > /tmp/tribbae-backend.pid
          echo "Backend démarré (PID $(cat /tmp/tribbae-backend.pid))"
      - echo "Démarrage du frontend..."
      - cmd: |
          cd frontend && npm run dev &
          echo $! > /tmp/tribbae-frontend.pid
          echo "Frontend démarré (PID $(cat /tmp/tribbae-frontend.pid))"
      - echo ""
      - echo "╔══════════════════════════════════════╗"
      - echo "║   Tribbae dev env démarré ✅          ║"
      - echo "║                                      ║"
      - echo "║  Frontend  → http://localhost:5173   ║"
      - echo "║  Backend   → http://localhost:8080   ║"
      - echo "║  Ollama    → http://localhost:11434  ║"
      - echo "╚══════════════════════════════════════╝"
      - echo ""
      - echo "Ctrl+C pour arrêter. Logs backend/frontend dans /tmp/tribbae-*.pid"
      - wait

  dev:stop:
    desc: "Arrêter le backend et le frontend (Ollama reste actif)"
    cmds:
      - cmd: |
          if [ -f /tmp/tribbae-backend.pid ]; then
            kill $(cat /tmp/tribbae-backend.pid) 2>/dev/null && echo "Backend arrêté" || true
            rm /tmp/tribbae-backend.pid
          fi
      - cmd: |
          if [ -f /tmp/tribbae-frontend.pid ]; then
            kill $(cat /tmp/tribbae-frontend.pid) 2>/dev/null && echo "Frontend arrêté" || true
            rm /tmp/tribbae-frontend.pid
          fi
